// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockAllocation.Infrastructure.Persistence;

#nullable disable

namespace StockAllocation.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721035848_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockAllocation.Domain.Entities.Allocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderLineId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockLotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderLineId");

                    b.HasIndex("StockLotId");

                    b.ToTable("Allocations", t =>
                        {
                            t.HasCheckConstraint("CK_Allocation_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("StockAllocation.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("StockAllocation.Domain.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique();

                    b.ToTable("OrderLines", t =>
                        {
                            t.HasCheckConstraint("CK_OrderLine_RequestedQuantity_Positive", "[RequestedQuantity] > 0");
                        });
                });

            modelBuilder.Entity("StockAllocation.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Blue Pen",
                            Sku = "PEN-001"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Notebook",
                            Sku = "NOTE-001"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Company Mug",
                            Sku = "MUG-001"
                        });
                });

            modelBuilder.Entity("StockAllocation.Domain.Entities.StockLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "BatchCode")
                        .IsUnique();

                    b.ToTable("StockLots", t =>
                        {
                            t.HasCheckConstraint("CK_StockLot_QuantityOnHand_NonNegative", "[QuantityOnHand] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchCode = "PEN-OLD",
                            ExpiresOn = new DateOnly(2000, 1, 1),
                            ProductId = 1,
                            QuantityOnHand = 100
                        },
                        new
                        {
                            Id = 2,
                            BatchCode = "PEN-A",
                            ExpiresOn = new DateOnly(2099, 1, 10),
                            ProductId = 1,
                            QuantityOnHand = 3
                        },
                        new
                        {
                            Id = 3,
                            BatchCode = "PEN-B",
                            ExpiresOn = new DateOnly(2099, 2, 10),
                            ProductId = 1,
                            QuantityOnHand = 5
                        },
                        new
                        {
                            Id = 4,
                            BatchCode = "NOTE-A",
                            ExpiresOn = new DateOnly(2099, 1, 5),
                            ProductId = 2,
                            QuantityOnHand = 2
                        },
                        new
                        {
                            Id = 5,
                            BatchCode = "NOTE-B",
                            ExpiresOn = new DateOnly(2099, 3, 1),
                            ProductId = 2,
                            QuantityOnHand = 10
                        },
                        new
                        {
                            Id = 6,
                            BatchCode = "MUG-A",
                            ExpiresOn = new DateOnly(2099, 12, 31),
                            ProductId = 3,
                            QuantityOnHand = 0
                        });
                });

            modelBuilder.Entity("StockAllocation.Domain.Entities.Allocation", b =>
                {
                    b.HasOne("StockAllocation.Domain.Entities.OrderLine", "OrderLine")
                        .WithMany("Allocations")
                        .HasForeignKey("OrderLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockAllocation.Domain.Entities.StockLot", "StockLot")
                        .WithMany("Allocations")
                        .HasForeignKey("StockLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderLine");

                    b.Navigation("StockLot");
                });

            modelBuilder.Entity("StockAllocation.Domain.Entities.OrderLine", b =>
                {
                    b.HasOne("StockAllocation.Domain.Entities.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockAllocation.Domain.Entities.Product", "Product")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockAllocation.Domain.Entities.StockLot", b =>
                {
                    b.HasOne("StockAllocation.Domain.Entities.Product", "Product")
                        .WithMany("StockLots")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockAllocation.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("StockAllocation.Domain.Entities.OrderLine", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("StockAllocation.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderLines");

                    b.Navigation("StockLots");
                });

            modelBuilder.Entity("StockAllocation.Domain.Entities.StockLot", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
